
# Install libraries  

library(dplyr)
library(ggplot2)
library(dslabs)

# Using 'heights' and 'murder' data'
data(heights)
data(murders)

# Making Canvas
p <- ggplot(data = murders)
p <- ggplot(murders)
p <- murders %>% ggplot()

class(p)


print(p)


p <- heights %>% ggplot()

class(p)

  
# Scatter plot 
murders %>% ggplot(aes(x=population, y=total)) +
  geom_point()


murders %>% ggplot(aes(total, population)) +
  geom_point()


# Scatter plot with labels
murders %>% ggplot(aes(population, total, label= abb))+geom_label()


murders %>% ggplot(aes(population, total, label= abb))+geom_label(color= "blue")

  
---------------------------------------------------------------------------

# Using 'us_contagious_diseases' data

library(dslabs)
data(us_contagious_diseases)



dat <- us_contagious_diseases %>%
  filter(year == 1967 & disease == "Measles" & !is.na(population)) %>%
  mutate(rate = count / population * 10000 *52 /weeks_reporting)  


dat %>% ggplot(aes(state, rate)) +
  geom_bar(stat= "identity") +
  coord_flip()



state <- dat$state
rate <- dat$count/dat$population*10000*52/dat$weeks_reporting


dat %>% mutate(state = reorder(state, rate)) %>%
  ggplot(aes(state, rate)) +
  geom_bar(stat= "identity") +
  coord_flip()

head(state)

---------------------------------------------------------------------------

#Download the gapminder data by callimg library(gapminder)


library(gapminder)
head(gapminder)


gapminder %>%
  group_by(continent) %>%
  summarize(count = n_distinct(country))

  

gapminder %>%
  filter(continent=="Europe",  year==1997&2007) %>%
  arrange(gdpPercap) %>%
  head(n=1)

gapminder %>%
  filter(between(year, 1980,1989)) %>%
  group_by(continent) %>%
  summarize(average = mean(lifeExp))

gapminder %>%
  mutate(GDP = gdpPercap * pop) %>%
  group_by(country) %>%
  summarize(totalgdp = sum(GDP)) %>%
  arrange(desc(totalgdp)) %>%
  head(n=5)

gapminder %>%
  select(country, lifeExp, year) %>%
  filter(80 <=lifeExp ) %>%
  print(n=Inf)

gapminder %>% 
  group_by(country) %>%
  summarize(abs_correlation = abs(cor(lifeExp,gdpPercap))) %>%
  arrange(desc(abs_correlation)) %>%
  head(n=10)


library(ggplot2)
diamonds

# Histogram
hist(diamonds$carat,col = "steel blue")

# Histogram(Change setting to bin = 30) 
qplot(diamonds$depth, bins = 30, geom = "histogram")

# Violin plot
diamonds %>% qplot(cut, price, data = ., geom = "violin", fill = cut)

  
  